In [1]:
import pandas as pd
import numpy as np

In [9]:
d = np.arange(0,10,3)

In [10]:
d

array([0, 3, 6, 9])

In [4]:
d<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [5]:
d[d<6]

array([0, 1, 2, 3, 4, 5])

In [6]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))



In [7]:
demo_matrix[:, (1,2)]



array([[35, 74],
       [37, 37],
       [39, 93]])

In [8]:
l = [[1,2],[3,4]]
np.array(l)

array([[1, 2],
       [3, 4]])

In [11]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])



In [12]:
flowers['daisy']

5

In [13]:
df3 = pd.DataFrame(np.random.randn(5,5),index=['first row','second row','third row','fourth row','fifth row'],
                   columns=['first col','second col','third col','fourth col','fifth col'])

In [14]:
df3

first col  second col  third col  fourth col  fifth col
first row   -0.868760   -0.915379   1.249648    0.047657  -0.158768
second row  -0.601730    1.276595  -1.243331    0.768781  -1.093427
third row    0.272800   -0.383802   0.514719   -0.838346  -1.615351
fourth row   0.075058   -0.744277   1.481909    0.283325  -1.722830
fifth row    1.030999    0.520857   0.529442   -0.122997   0.485161

In [15]:
df3['sixth col'] = np.arange(5)

In [24]:
df3.drop('sixth col',axis=1,inplace=True)

In [25]:
df3

first col  second col  third col  fourth col  fifth col
first row   -0.868760   -0.915379   1.249648    0.047657  -0.158768
second row  -0.601730    1.276595  -1.243331    0.768781  -1.093427
third row    0.272800   -0.383802   0.514719   -0.838346  -1.615351
fourth row   0.075058   -0.744277   1.481909    0.283325  -1.722830
fifth row    1.030999    0.520857   0.529442   -0.122997   0.485161

In [32]:
flowers = pd.Series([2, 3, 5, 4])
flowers1 = pd.Series([21, 31, 51, 41])


In [33]:
pd.concat([flowers,flowers1])

0     2
1     3
2     5
3     4
0    21
1    31
2    51
3    41
dtype: int64

In [34]:
pd.read_csv?